services:

  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspaces/tagging-service:cached
    command: sleep infinity
    networks:
      - devnet
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnet
    ports:
      - "5432:5432"

networks:
  devnet:


volumes:
  postgres-data:
