title: Tag Management System Documentation
description: REST API and database schema for the Tag Management System.
baseurl: "/tag-management-system"
url: "https://kmahabeer.github.io"
remote_theme: just-the-docs/just-the-docs

# Navigation & UI
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/kmahabeer/tag-management-system"
nav_sort: case_insensitive

collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
      has_children: false
