title: Tag Management System
description: REST API and database schema for the Tag Management System.
baseurl: "/tag-management-system"
url: "https://kmahabeer.github.io"
remote_theme: just-the-docs/just-the-docs

# Navigation & UI
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/kmahabeer/tag-management-system"
nav_sort: case_insensitive
nav_enabled: true

mermaid:
  version: "11.12.0"
